pipelines:
  - name: testJenkins
    steps:
      - name: firstBashStep
        type: Bash 
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - sleep 5s
      - name: testStepJenkins
        type: Jenkins
        configuration:
          inputSteps:
            - name: firstBashStep
          jenkinsJobName: testPipeline 
          integrations:
            - name: S_B_Jenkins
      - name: secondBashStep
        type: Bash 
        configuration:
          inputSteps:
            - name: testStepJenkins
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - echo "executing onExecute"
