pipelines:
  - name: testJenkins
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
          timeoutSeconds: 2
          jenkinsJobName: testPipeline
          integrations:
            - name: S_B_Jenkins
