pipelines:
  - name: testJenkins
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline
          integrations:
            - name: jenkins
      - name: testBashStep
        type: Bash 
        configuration:
          inputSteps:
            - name: testStepJenkins
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - sleep 5s
