# pipelines:
#   - name: testJenkinsTrigger
#     steps:
#       - name: testStepJenkins
#         type: Jenkins
#         configuration:
#           jenkinsJobName: sampleJob  
#           integrations:
#             - name: jenkins
pipelines:
  - name: S_B_Jen_0002_pipelines
    steps:
      - name: S_B_Jen_0002                 
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline  
          jenkinsBranchName: test 
          buildParameters:
            key1: value1
            key2: value2            
          integrations:
            - name: S_B_Jenkins 
