pipelines:
  - name: testJenkinsTrigger
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
          jenkinsJobName: test
          buildParameters:
            foo1: bar1
            foo2: bar2  
          integrations:
            - name: jenkins
