resources:
  - name: valueStore
    type: PropertyBag
    configuration:
      foo: bar
pipelines:
  - name: testJenkins
    steps:
      - name: bashStep
        type: Bash 
        outputResources:
            - name: valueStore
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - sleep 2s
      - name: jenkinsStep
        type: Jenkins
        configuration:
          inputSteps:
            - name: bashStep
          inputResources:
            - name: valueStore
          jenkinsJobName: testPipeline
          buildParameters:
            foo1: bar1 
          integrations:
            - name: jenkins
