
pipelines:
  - name: testJenkins
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline  
          integrations:
            - name: S_B_Jenkins
