# pipelines:
#   - name: testJenkinsTrigger
#     steps:
#       - name: testStepJenkins
#         type: Jenkins
#         configuration:
#           jenkinsJobName: sampleJob  
#           integrations:
#             - name: jenkins
pipelines:
  - name: S_B_Jen_0001_pipelines

    steps:
      - name: S_B_Jen_0001
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline
          integrations:
            - name: S_B_Jenkins
