pipelines:
  - name: testJenkins
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
          inputSteps:
            - name: reqStepJenkins
          jenkinsJobName: testPipeline  
          integrations:
            - name: S_B_Jenkins
      - name: reqStepJenkins
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline  
          integrations:
            - name: S_B_Jenkins
