pipelines:
  - name: testJenkins
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
          timeoutSeconds: 2
          jenkinsJobName: testPipeline
          buildParameters:
            foo1: bar1
            foo2: bar2  
          integrations:
            - name: jenkins
