# pipelines:
#   - name: pipeline
#     steps:
#       - name: psStep
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#         execution:
#           onStart:
#             - echo "hello"
resources:
 - name: resource_pipelines_1
   type: GitRepo
   configuration:
     gitProvider: github_neha
     path: neha-mishraa/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$

pipelines:
  - name: testcustom
    steps:
      - name: myStep1
        type: Bash
        configuration:
         inputResources: 
           - name: resource_pipelines
         integrations:
           - name: github_neha
        execution:
          onExecute:
            - pushd $res_resource_pipelines_1_resourcePath
            - ls
            - echo "hi"

  - name: qwerty123
    steps:
      - name: myStep2
        type: Bash
        configuration:
         integrations:
           - name: github_neha
        execution:
          onExecute:
            - echo "hi"
  - name: neha23custom
    steps:
      - name: myStep3
        type: Bash
        execution:
          onExecute:
            - echo "hi"
