pipelines:
  - name: pipeline
    steps:
      - name: psStep
        type: PowerShell
        configuration:
          nodePool: win_2019
        execution:
          onStart:
            - echo "hello"
