# pipelines:
#   - name: pipeline
#     steps:
#       - name: psStep
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#         execution:
#           onStart:
#             - echo "hello"
resources:
 - name: resource_pipelines
   type: GitRepo
   configuration:
     gitProvider: github_neha
     path: neha-mishraa/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
#      buildOn:
#        commit: true

pipelines:
  - name: pipe1
    steps:
      - name: myStep1
        type: Bash
        configuration:
         inputResources: 
           - name: resource_pipelines
         integrations:
           - name: github_neha
#            - name: slackTest
#            - name: smtpNotification
        execution:
          onExecute:
#             - printenv
            - pushd $res_resource_pipelines_resourcePath
            - ls
            - echo "hi"
#             - send_notification slackTest --text "Pipeline test"
#             - send_notification smtpNotification --recipients "nehamishraj01@gmail.com" --subject "Build Succeeded" --body "Message received"

#           onSuccess:
#             - pushd $res_resource_pipelines_resourcePath
#             - ls

  - name: testpipe2
    steps:
      - name: myStep2
        type: Bash
        configuration:
         integrations:
           - name: github_neha
        execution:
          onExecute:
            - echo "hi"
   - name: nehatest
    steps:
      - name: myStep3
        type: Bash
        execution:
          onExecute:
            - echo "hi"
