resources:
  - name: S_GoPublishBinary_0024_GitRepo_res
    type: GitRepo
    configuration:
      gitProvider: github_neha
      path: jfbetapipeorg/Org_test_Automation_bash
      branches:
        include: main

pipelines:
  - name: pipeline_S_GoPublishBinary_0024_pipe
    steps:
      - name: S_GoPublishBinary_0024_1
        type: GoBuild
        configuration:
          inputResources:
            - name: S_GoPublishBinary_0024_GitRepo_res
          integrations:
            - name: s_artifactory
          sourceLocation: "tests/Go/HelloWorld"
          resolverRepo: test-automation-go-virtual
      - name: S_GoPublishBinary_0024_2
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: S_GoPublishBinary_0024_1
          integrations:
            - name: s_artifactory
          targetRepository: test-automation-go-local
